---
relationships:
  - relationship_when: "{{ ((_resource['values']['ip_configuration'] | default([]) | selectattr('primary', 'equalto', true) | map(attribute='subnet_id') | first |
      default('', true)) | length) > 0 }}"
    parent: "{{ _resource['values']['id'] }}"
    parent_type: cmdb_ci_nic
    type: IP Connection::IP Connection
    child: "{{ _resource['values']['ip_configuration'] | default([]) | selectattr('primary', 'equalto', true) | map(attribute='subnet_id') | first }}"
    child_type: cmdb_ci_subnet
  - relationship_when: "{{ ((_resource['values']['virtual_machine_id'] | default('')) | length) > 0 }}"
    parent: "{{ _resource['values']['virtual_machine_id'] }}"
    parent_type: cmdb_ci_vm_instance
    type: IP Connection::IP Connection
    child: "{{ _resource['values']['id'] }}"
    child_type: cmdb_ci_nic
