---
- name: Configure web server
  hosts: tag_demo_web
  become: true

  vars_files:
    - vars/main.yml

  tasks:
    - name: Install httpd
      ansible.builtin.package:
        name: httpd
        state: present

    - name: Start and enable httpd service
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started

    - name: Allow http traffic
      ansible.posix.firewalld:
        port: 80/tcp
        permanent: true
        immediate: true
        state: enabled
        zone: public

    - name: Create a custom index.html file
      vars:
        subtitle: "running on azure vm {{ computer_name }} @ {{ public_ip_address }}"
      ansible.builtin.template:
        dest: /var/www/html/index.html
        src: index.html.j2

    - name: Check out the site
      run_once: true
      ansible.builtin.set_fact:
        sn_work_notes: >-
          [code]{% for host in ansible_play_hosts %}
          <p>Web server deployed on <strong>{{ host }}</strong><br>
          <a href="http://{{ hostvars[host]['public_ip_addresses'] }}">View Site</a></p>
          {% endfor %}[/code]

    - name: Set stats for task update
      when: sc_task_created is defined and r_tf_apply is defined
      ansible.builtin.set_stats:
        aggregate: false
        data:
          update_sc_task_sys_id: "{{ sc_task_created.sys_id }}"
          update_sc_task_data:
            work_notes:  "{{ sn_work_notes }}"
            close_notes: Web server(s) configuration complete
            state: 3 # Closed complete