---
- name: Configure web server
  hosts: tag_demo_web
  become: true

  vars_files:
    - vars/main.yml

  tasks:
    - name: Install httpd
      ansible.builtin.package:
        name: httpd
        state: present

    - name: Start and enable httpd service
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started

    - name: Allow http traffic
      ansible.posix.firewalld:
        port: 80/tcp
        permanent: true
        immediate: true
        state: enabled
        zone: public

    - name: Create a custom index.html file
      vars:
        subtitle: "running on azure vm {{ computer_name }} @ {{ public_ip_address }}"
      ansible.builtin.template:
        dest: /var/www/html/index.html
        src: index.html.j2

    - name: Set stats for task update
      delegate_to: localhost
      when: sc_task_created is defined
      ansible.builtin.set_stats:
        aggregate: false
        data:
          update_sc_task_sys_id: "{{ sc_task_created[inventory_hostname]['sys_id'] }}"
          update_sc_task_data:
            work_notes:  >-
              [code]
              <p>Web server deployed on <strong>{{ host }}</strong><br>
              <a href="http://{{ hostvars[host]['public_ip_address'] }}">View Site</a></p>
              [/code]
            close_notes: Web server configuration complete
            state: 3 # Closed complete
