---
- name: Terraform operations
  hosts: localhost
  gather_facts: false
  become: false

  vars:
    tf_project_dir: "{{ playbook_dir | dirname }}"
    tf_workspace: "{{ lookup('ansible.builtin.env', 'TF_WORKSPACE') | default(false) }}"

  tasks:
    - name: Assert workspace provided
      ansible.builtin.assert:
        that: tf_workspace
        fail_msg: "ansible var tf_workspace or env var TF_WORKSPACE must be provided"

    - name: Terraform apply | create_web_demo
      register: r_tf_apply
      cloud.terraform.terraform:
        project_path: "{{ tf_project_dir }}"
        state: present
        force_init: true
        workspace: "{{ tf_workspace }}"
        variables:
          web_demo_ssh_pubkey: "{{ az_ssh_pubkey }}"
          web_vm_size: "{{ az_web_vm_size | default('Standard_DS1_v2') }}"

    - name: Terraform destroy | create_web_demo
      tags: [never, remove]
      register: r_tf_destroy
      cloud.terraform.terraform:
        project_path: "{{ tf_project_dir }}"
        state: absent
        force_init: true
        workspace: "{{ tf_workspace }}"
        variables:
          web_demo_ssh_pubkey: "{{ az_ssh_pubkey }}"
          web_vm_size: "{{ az_web_vm_size | default('Standard_DS1_v2') }}"

    - name: Prep stats for task update
      when: sc_task_created is defined and r_tf_apply is defined
      ansible.builtin.set_fact:
        update_sc_task_sys_id: "{{ sc_task_created[inventory_hostname]['sys_id'] }}"
        update_sc_task_data:
          work_notes:  "{{ r_tf_apply['outputs']['azure_web_demo_vm_details']['value'] | to_nice_json(indent=2) | codify }}"
          close_notes: Terraform deployment completed
          state: 3 # Closed complete

    - name: Set stats for web server task create
      when: r_tf_apply is defined
      ansible.builtin.set_stats:
        data: >
          {
            "create_sc_task_data_overrides": {
              {% for vm in r_tf_apply['outputs']['azure_web_demo_vm_details']['value'] %}
              "{{ vm.name }}": {"short_description":"Ansible initiating configuration of {{ vm }}"}
              {% if not loop.last %},{% endif %}
              {% endfor %}
            }
          }
